#!/usr/bin/env python3
"""Export dist/codex system prompts as Codex CLI custom agent TOML files."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import tomllib
import unicodedata
from pathlib import Path


ROOT = Path(__file__).parent.parent
SOURCE_ROOT = ROOT / "dist" / "codex"
AGENTS_DIR = ROOT / ".codex" / "agents"
CONFIG_PATH = ROOT / ".codex" / "config.toml"
GENERATED_HEADER = "# Generated by scripts/export-codex-agents.py; do not edit manually."

KNOWN_SLUGS = {
    "01-สถาปนิกแบ็กเอนด์": "backend-architect",
    "02-นักพัฒนาอาวุโส": "senior-developer",
    "03-สถาปนิกซอฟต์แวร์": "software-architect",
    "สถาปนิกแบ็กเอนด์": "backend-architect",
    "นักพัฒนาอาวุโส": "senior-developer",
    "สถาปนิกซอฟต์แวร์": "software-architect",
}

ACRONYMS = {
    "api": "API",
    "cfo": "CFO",
    "cmo": "CMO",
    "defi": "DeFi",
    "qa": "QA",
    "ui": "UI",
    "ux": "UX",
    "web3": "Web3",
}


def toml_string(value: str) -> str:
    """Return an escape-safe TOML basic string."""
    return json.dumps(value, ensure_ascii=False)


def strip_numeric_prefix(value: str) -> str:
    return re.sub(r"^\d+[-_]+", "", value)


def slugify(value: str, fallback_key: str = "agent", strip_prefix: bool = True) -> str:
    value = KNOWN_SLUGS.get(value, value)
    if strip_prefix:
        value = strip_numeric_prefix(value)
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-{2,}", "-", value).strip("-")
    if value:
        return value
    digest = hashlib.sha1(fallback_key.encode("utf-8")).hexdigest()[:8]
    return f"agent-{digest}"


def title_from_slug(value: str) -> str:
    words = slugify(value).split("-")
    titled = [ACRONYMS.get(word, word.title()) for word in words]
    return " ".join(titled)


def extract_field(content: str, field: str) -> str:
    match = re.search(rf"^{re.escape(field)}:[ \t]*(.*)$", content, re.MULTILINE)
    return match.group(1).strip() if match else ""


def prompt_paths() -> list[Path]:
    return sorted(SOURCE_ROOT.rglob("system_prompt.md"))


def agent_name_for(path: Path) -> str:
    rel_parent = path.parent.relative_to(SOURCE_ROOT)
    parts = rel_parent.parts
    department = slugify(parts[0], str(rel_parent), strip_prefix=False)

    if parts[-1] == "head":
        role = "head"
    else:
        role = slugify(parts[-1], str(rel_parent))

    return f"{department}-{role}"


def description_for(path: Path, content: str) -> str:
    rel_parent = path.parent.relative_to(SOURCE_ROOT)
    parts = rel_parent.parts
    department = title_from_slug(parts[0])
    role = extract_field(content, "Role") or title_from_slug(parts[-1])

    if parts[-1] == "head":
        return (
            f"Department head for {department}; use for scoping, delegation, "
            "review, and handoff decisions."
        )

    if role.lower() == department.lower():
        return f"{role} specialist; use for focused work in this domain."

    return f"{role} specialist for {department}; use for focused work in this domain."


def agent_toml(path: Path, name: str, description: str, instructions: str) -> str:
    source = path.relative_to(ROOT)
    return "\n".join(
        [
            GENERATED_HEADER,
            f"# Source: {source}",
            f"name = {toml_string(name)}",
            f"description = {toml_string(description)}",
            f"developer_instructions = {toml_string(instructions)}",
            "",
        ]
    )


def remove_stale_generated_files(expected: set[Path]) -> None:
    for path in AGENTS_DIR.glob("*.toml"):
        if path in expected:
            continue
        first_line = path.read_text(encoding="utf-8").splitlines()[:1]
        if first_line and first_line[0] == GENERATED_HEADER:
            path.unlink()


def validate_config() -> None:
    tomllib.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def validate_agents() -> int:
    names: set[str] = set()
    for path in sorted(AGENTS_DIR.glob("*.toml")):
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        for key in ("name", "description", "developer_instructions"):
            if not data.get(key):
                raise ValueError(f"{path}: missing {key}")
        name = data["name"]
        if name in names:
            raise ValueError(f"duplicate agent name: {name}")
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", name):
            raise ValueError(f"{path}: agent name is not an ASCII slug: {name}")
        names.add(name)
    return len(names)


def export_agents() -> int:
    AGENTS_DIR.mkdir(parents=True, exist_ok=True)

    paths = prompt_paths()
    if not paths:
        raise RuntimeError(f"no system_prompt.md files found under {SOURCE_ROOT}")

    names: set[str] = set()
    outputs: dict[Path, str] = {}
    for source_path in paths:
        content = source_path.read_text(encoding="utf-8").strip()
        name = agent_name_for(source_path)
        if name in names:
            rel = source_path.parent.relative_to(SOURCE_ROOT)
            digest = hashlib.sha1(str(rel).encode("utf-8")).hexdigest()[:8]
            name = f"{name}-{digest}"
        names.add(name)

        description = description_for(source_path, content)
        outputs[AGENTS_DIR / f"{name}.toml"] = agent_toml(
            source_path,
            name,
            description,
            content,
        )

    remove_stale_generated_files(set(outputs))

    for path, content in sorted(outputs.items()):
        path.write_text(content, encoding="utf-8")

    return len(outputs)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export dist/codex prompts into .codex/agents/*.toml."
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Validate existing .codex config and agent TOML files without writing.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    count = 0 if args.validate_only else export_agents()
    validate_config()
    validated = validate_agents()
    if args.validate_only:
        print(f"OK: validated {validated} agents")
    else:
        print(f"OK: exported {count} agents and validated {validated} agents")


if __name__ == "__main__":
    main()
